name: e_repairkit
owner: Denzel Quah
description: "Package for e_repairkit app"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
      sdk: flutter

  provider: ^6.1.5+1
  google_generative_ai: ^0.4.7
  flutter_dotenv: ^5.1.0
  firebase_core: any
  cloud_firestore: any
  async: ^2.12.0
  location: any
  http: any



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env